apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: bff:latest
        imagePullPolicy: Never # For local dev
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: USER_SERVICE_URL
          value: "user-service:50051"
        - name: POST_SERVICE_URL
          value: "post-service:50052"
---
apiVersion: v1
kind: Service
metadata:
  name: bff
spec:
  selector:
    app: bff
  type: LoadBalancer # Expose to host for frontend to access
  ports:
  - port: 8080
    targetPort: 8080
